import { Study, TeamMember, CommunityItem, LabSettings } from './types';

export function getSeedStudies(): Study[] {
  return [
    {
      id: 'study-1',
      name: 'Détection précoce de la dépression par la voix',
      description:
        'Étude multimodale visant à identifier des biomarqueurs vocaux associés aux épisodes dépressifs majeurs. Le protocole combine des enregistrements audio, des questionnaires standardisés (PHQ-9, GAD-7) et une interaction conversationnelle avec un agent IA.',
      tags: ['dépression', 'voix', 'biomarqueurs', 'IA', 'santé mentale'],
      status: 'publiee',
      createdAt: '2025-11-15T10:00:00Z',
      updatedAt: '2026-03-20T14:30:00Z',
      ethicsApprovalFileName: 'approbation_ethique_depression_voix.pdf',
      consentConfigured: true,
      recruitmentTarget: 100,
      recruitedCount: 45,
      protocol: {
        id: 'proto-1',
        version: '1.2',
        modules: [
          {
            id: 'mod-1-1',
            name: 'Questionnaire démographique',
            description: 'Collecte des informations sociodémographiques du participant',
            order: 0,
            questions: [
              {
                id: 'q-1-1-1',
                type: 'qcm',
                label: 'Tranche d\'âge',
                consigne: { type: 'texte', content: 'Veuillez sélectionner votre tranche d\'âge.' },
                required: true,
                options: ['18-25 ans', '26-35 ans', '36-45 ans', '46-55 ans', '56-65 ans', '65+ ans'],
                order: 0,
                eligibility: {
                  enabled: true,
                  rules: [
                    { answer: '18-25 ans', effect: 'include' },
                    { answer: '26-35 ans', effect: 'include' },
                    { answer: '36-45 ans', effect: 'include' },
                    { answer: '46-55 ans', effect: 'include' },
                    { answer: '56-65 ans', effect: 'include' },
                    { answer: '65+ ans', effect: 'exclude' },
                  ],
                },
              },
              {
                id: 'q-1-1-2',
                type: 'qcm',
                label: 'Niveau d\'éducation',
                consigne: { type: 'texte', content: 'Quel est votre plus haut niveau de diplôme obtenu ?' },
                required: true,
                options: ['Secondaire', 'Collégial/CÉGEP', 'Baccalauréat', 'Maîtrise', 'Doctorat'],
                order: 1,
              },
              {
                id: 'q-1-1-3',
                type: 'qcm',
                label: 'Sexe',
                consigne: { type: 'texte', content: 'Quel est votre sexe ?' },
                required: true,
                options: ['Homme', 'Femme', 'Non-binaire', 'Préfère ne pas répondre'],
                order: 2,
                eligibility: {
                  enabled: true,
                  rules: [
                    { answer: 'Homme', effect: 'include' },
                    { answer: 'Femme', effect: 'include' },
                    { answer: 'Non-binaire', effect: 'include' },
                    { answer: 'Préfère ne pas répondre', effect: 'exclude' },
                  ],
                },
              },
            ],
          },
          {
            id: 'mod-1-2',
            name: 'Évaluation PHQ-9',
            description: 'Questionnaire standardisé de dépistage de la dépression',
            order: 1,
            questions: [
              {
                id: 'q-1-2-1',
                type: 'likert',
                label: 'Peu d\'intérêt ou de plaisir à faire les choses',
                consigne: { type: 'texte', content: 'Au cours des 2 dernières semaines, à quelle fréquence avez-vous été gêné(e) par le problème suivant ?' },
                required: true,
                options: ['Jamais', 'Plusieurs jours', 'Plus de la moitié du temps', 'Presque tous les jours'],
                order: 0,
              },
              {
                id: 'q-1-2-2',
                type: 'likert',
                label: 'Sentiment de déprime, de dépression ou de désespoir',
                consigne: { type: 'texte', content: 'Au cours des 2 dernières semaines, à quelle fréquence avez-vous été gêné(e) par le problème suivant ?' },
                required: true,
                options: ['Jamais', 'Plusieurs jours', 'Plus de la moitié du temps', 'Presque tous les jours'],
                order: 1,
              },
              {
                id: 'q-1-2-3',
                type: 'likert',
                label: 'Difficultés à s\'endormir ou à rester endormi(e)',
                consigne: { type: 'texte', content: 'Au cours des 2 dernières semaines, à quelle fréquence avez-vous été gêné(e) par le problème suivant ?' },
                required: true,
                options: ['Jamais', 'Plusieurs jours', 'Plus de la moitié du temps', 'Presque tous les jours'],
                order: 2,
              },
            ],
          },
          {
            id: 'mod-1-3',
            name: 'Enregistrement vocal',
            description: 'Tâches d\'enregistrement audio pour l\'analyse vocale',
            order: 2,
            questions: [
              {
                id: 'q-1-3-1',
                type: 'audio',
                label: 'Description d\'image',
                consigne: { type: 'image', content: 'Décrivez cette image en parlant à voix haute pendant au moins 30 secondes.' },
                required: true,
                order: 0,
              },
              {
                id: 'q-1-3-2',
                type: 'audio',
                label: 'Lecture de texte',
                consigne: { type: 'texte', content: 'Veuillez lire le passage suivant à voix haute : "Le soleil se levait doucement sur la ville endormie. Les rues étaient encore silencieuses, à l\'exception du chant matinal des oiseaux."' },
                required: true,
                order: 1,
              },
            ],
          },
          {
            id: 'mod-1-4',
            name: 'Interaction IA',
            description: 'Conversation avec un agent conversationnel pour évaluation sémantique',
            order: 3,
            questions: [
              {
                id: 'q-1-4-1',
                type: 'ia',
                label: 'Conversation libre',
                consigne: { type: 'texte', content: 'Engagez une conversation avec notre assistant virtuel. Parlez librement de votre semaine, de vos activités et de votre état d\'esprit actuel. La conversation durera environ 5 minutes.' },
                required: true,
                order: 0,
              },
            ],
          },
        ],
      },
    },
    {
      id: 'study-2',
      name: 'Suivi cognitif post-AVC',
      description:
        'Protocole longitudinal de suivi des fonctions cognitives après un accident vasculaire cérébral. Combine des tests neuropsychologiques classiques avec des mesures vidéo de l\'expression faciale et de la motricité fine.',
      tags: ['AVC', 'cognition', 'neuropsychologie', 'vidéo', 'longitudinal'],
      status: 'brouillon',
      createdAt: '2026-02-01T09:00:00Z',
      updatedAt: '2026-03-25T16:00:00Z',
      consentConfigured: false,
      recruitmentTarget: 50,
      recruitedCount: 0,
      protocol: {
        id: 'proto-2',
        version: '0.3',
        modules: [
          {
            id: 'mod-2-1',
            name: 'Évaluation cognitive de base',
            description: 'Tests cognitifs standardisés (MoCA adapté)',
            order: 0,
            questions: [
              {
                id: 'q-2-1-1',
                type: 'video_visionnage',
                label: 'Instructions vidéo',
                consigne: { type: 'video', content: 'Regardez attentivement cette vidéo d\'instructions avant de commencer les tests.' },
                required: true,
                order: 0,
              },
              {
                id: 'q-2-1-2',
                type: 'qcm',
                label: 'Orientation temporelle',
                consigne: { type: 'texte', content: 'Quelle est la date d\'aujourd\'hui ?' },
                required: true,
                options: ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche'],
                order: 1,
              },
              {
                id: 'q-2-1-3',
                type: 'texte',
                label: 'Rappel de mots',
                consigne: { type: 'texte', content: 'Écrivez les 5 mots que vous avez mémorisés lors de l\'exercice précédent.' },
                required: true,
                order: 2,
              },
            ],
          },
          {
            id: 'mod-2-2',
            name: 'Analyse d\'expression faciale',
            description: 'Enregistrement vidéo pendant des tâches émotionnelles',
            order: 1,
            questions: [
              {
                id: 'q-2-2-1',
                type: 'video',
                label: 'Expression émotionnelle',
                consigne: { type: 'texte', content: 'En regardant la caméra, exprimez les émotions suivantes : joie, surprise, tristesse. Attendez 5 secondes entre chaque émotion.' },
                required: true,
                order: 0,
              },
              {
                id: 'q-2-2-2',
                type: 'video',
                label: 'Motricité faciale',
                consigne: { type: 'texte', content: 'Effectuez les mouvements suivants devant la caméra : sourire large, froncer les sourcils, ouvrir grand la bouche, fermer les yeux fort.' },
                required: true,
                order: 1,
              },
            ],
          },
          {
            id: 'mod-2-3',
            name: 'Bien-être subjectif',
            description: 'Questionnaire sur le bien-être et la qualité de vie',
            order: 2,
            questions: [
              {
                id: 'q-2-3-1',
                type: 'likert',
                label: 'Satisfaction globale',
                consigne: { type: 'texte', content: 'Comment évaluez-vous votre qualité de vie globale actuellement ?' },
                required: true,
                options: ['Très mauvaise', 'Mauvaise', 'Moyenne', 'Bonne', 'Très bonne'],
                order: 0,
              },
              {
                id: 'q-2-3-2',
                type: 'texte',
                label: 'Commentaires libres',
                consigne: { type: 'texte', content: 'Y a-t-il quelque chose que vous aimeriez nous partager concernant votre rétablissement ?' },
                required: false,
                order: 1,
              },
            ],
          },
        ],
      },
    },
    {
      id: 'study-3',
      name: 'Biomarqueurs vocaux du stress chronique',
      description:
        'Étude terminée ayant collecté des données vocales et physiologiques auprès de 200 professionnels de santé pour développer un modèle de détection du stress chronique par la voix.',
      tags: ['stress', 'voix', 'professionnels de santé', 'biomarqueurs', 'modèle IA'],
      status: 'terminee',
      createdAt: '2025-06-01T08:00:00Z',
      updatedAt: '2026-01-15T11:00:00Z',
      ethicsApprovalFileName: 'approbation_ethique_stress_vocal.pdf',
      consentConfigured: true,
      recruitmentTarget: 200,
      recruitedCount: 200,
      protocol: {
        id: 'proto-3',
        version: '2.0',
        modules: [
          {
            id: 'mod-3-1',
            name: 'Profil professionnel',
            description: 'Informations sur le contexte professionnel',
            order: 0,
            questions: [
              {
                id: 'q-3-1-1',
                type: 'qcm',
                label: 'Profession',
                consigne: { type: 'texte', content: 'Quelle est votre profession ?' },
                required: true,
                options: ['Médecin', 'Infirmier(ère)', 'Psychologue', 'Travailleur social', 'Autre'],
                order: 0,
              },
              {
                id: 'q-3-1-2',
                type: 'likert',
                label: 'Niveau de stress perçu',
                consigne: { type: 'texte', content: 'Sur une échelle, comment évaluez-vous votre niveau de stress actuel au travail ?' },
                required: true,
                options: ['Très faible', 'Faible', 'Modéré', 'Élevé', 'Très élevé'],
                order: 1,
              },
            ],
          },
          {
            id: 'mod-3-2',
            name: 'Échantillons vocaux',
            description: 'Enregistrements vocaux dans différentes conditions',
            order: 1,
            questions: [
              {
                id: 'q-3-2-1',
                type: 'audio',
                label: 'Voyelle soutenue',
                consigne: { type: 'texte', content: 'Prononcez la voyelle "Ahhh" de manière continue pendant 10 secondes.' },
                required: true,
                order: 0,
              },
              {
                id: 'q-3-2-2',
                type: 'audio',
                label: 'Description de journée',
                consigne: { type: 'texte', content: 'Décrivez votre journée de travail typique en 1 à 2 minutes.' },
                required: true,
                order: 1,
              },
              {
                id: 'q-3-2-3',
                type: 'audio',
                label: 'Lecture standardisée',
                consigne: { type: 'texte', content: 'Lisez le texte suivant à voix haute : "Le vent du nord soufflait avec force. Les arbres pliaient sous sa puissance, mais aucun ne cédait."' },
                required: true,
                order: 2,
              },
            ],
          },
        ],
      },
    },
  ];
}

export function getSeedTeam(): TeamMember[] {
  return [
    {
      id: 'tm-1',
      name: 'Dr. Bérengère Houzé',
      email: 'berengere.houze@apertum.io',
      role: 'chercheur_principal',
      avatar: 'BH',
    },
    {
      id: 'tm-2',
      name: 'Pierre-Briac Metayer',
      email: 'pb.metayer@apertum.io',
      role: 'chercheur_principal',
      avatar: 'PM',
    },
    {
      id: 'tm-3',
      name: 'Marie-Claire Dupont',
      email: 'mc.dupont@criugm.ca',
      role: 'collaborateur',
      avatar: 'MD',
    },
    {
      id: 'tm-4',
      name: 'Alexandre Tremblay',
      email: 'a.tremblay@umontreal.ca',
      role: 'collaborateur',
      avatar: 'AT',
    },
    {
      id: 'tm-5',
      name: 'Sophie Lavoie',
      email: 's.lavoie@umontreal.ca',
      role: 'assistant',
      avatar: 'SL',
    },
  ];
}

export function getSeedCommunity(): CommunityItem[] {
  return [
    {
      id: 'comm-1',
      type: 'dataset',
      name: 'VoiceDepression-500',
      description: 'Dataset de 500 enregistrements vocaux annotés pour la détection de la dépression. Inclut des métadonnées démographiques et des scores PHQ-9.',
      author: 'Laboratoire LINGUA — UdeM',
      downloads: 342,
      tags: ['dépression', 'audio', 'PHQ-9'],
      createdAt: '2025-09-15T00:00:00Z',
    },
    {
      id: 'comm-2',
      type: 'dataset',
      name: 'StressVocal-Pro',
      description: 'Corpus de 1200 échantillons vocaux de professionnels de santé avec mesures de cortisol salivaire associées.',
      author: 'CESH — UdeM',
      downloads: 189,
      tags: ['stress', 'voix', 'cortisol', 'professionnels'],
      createdAt: '2025-12-01T00:00:00Z',
    },
    {
      id: 'comm-3',
      type: 'protocole',
      name: 'Protocole MoCA numérique',
      description: 'Version numérique du Montreal Cognitive Assessment adaptée pour la collecte en ligne avec support audio/vidéo.',
      author: 'CRIUGM',
      downloads: 567,
      tags: ['cognition', 'MoCA', 'neuropsychologie'],
      createdAt: '2025-08-20T00:00:00Z',
    },
    {
      id: 'comm-4',
      type: 'protocole',
      name: 'Batterie émotionnelle multimodale',
      description: 'Protocole complet d\'évaluation émotionnelle combinant questionnaires, enregistrements vidéo et tâches de reconnaissance faciale.',
      author: 'CESCNOV — UdeM',
      downloads: 234,
      tags: ['émotions', 'multimodal', 'vidéo', 'reconnaissance faciale'],
      createdAt: '2026-01-10T00:00:00Z',
    },
    {
      id: 'comm-5',
      type: 'modele',
      name: 'VocalBiomarker-Depression v2.1',
      description: 'Modèle de classification binaire (dépression/contrôle) basé sur des features acoustiques extraites de la voix. AUC = 0.87.',
      author: 'Apertum OBNL',
      downloads: 128,
      tags: ['IA', 'dépression', 'voix', 'classification'],
      createdAt: '2026-02-15T00:00:00Z',
    },
    {
      id: 'comm-6',
      type: 'modele',
      name: 'StressPredictor-Audio v1.0',
      description: 'Modèle de régression prédisant le niveau de stress perçu à partir de caractéristiques prosodiques. R² = 0.72.',
      author: 'Apertum OBNL',
      downloads: 95,
      tags: ['IA', 'stress', 'prosodie', 'régression'],
      createdAt: '2026-03-01T00:00:00Z',
    },
  ];
}

export function getDefaultLabSettings(): LabSettings {
  return {
    labName: 'Laboratoire PCAN — CRIUGM',
    email: 'contact@apertum.io',
    timezone: 'America/Montreal',
  };
}
